site:
  title: "MFAB"
  author: "Murilo"
  baseURL: "/"
  description: "Descrição"
  menus:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Notes"
      url: "/notes"
      weight: 2
    - name: "About"
      url: "/about"
      weight: 3

content_types:
  posts:
    sortBy: "date"
    sortReverse: true
    dateInURL: true
  notes:
    sortBy: "title"
    sortReverse: false
    dateInURL: false

socials:
  - name: "GitHub"
    icon: "github"
    url: "https://github.com/Murilo-fab"
  - name: "Twitter"
    icon: "twitter"
    url: "https://twitter.com/murilo_fab"